apiVersion: apps/v1
kind: Deployment
metadata:
  name: archburgers-app-deployment
spec:
  selector:
    matchLabels:
      app: archburgers-app
  replicas: 1
  template:
    metadata:
      labels:
        app: archburgers-app
    spec:
      containers:
        - name: archburgers-app-container
          image: gomesrodris/architect-burgers:0.0.4
          ports:
            - containerPort: 8090
          env:
            - name: "archburgers.datasource.driverClass"
              valueFrom:
                configMapKeyRef:
                  name: "archburgers-db-access-config"
                  key: "archburgers.datasource.driverClass"
            - name: "archburgers.datasource.dbUrl"
              valueFrom:
                configMapKeyRef:
                  name: "archburgers-db-access-config"
                  key: "archburgers.datasource.dbUrl"
            - name: "archburgers.datasource.dbUser"
              valueFrom:
                configMapKeyRef:
                  name: "archburgers-db-access-config"
                  key: "archburgers.datasource.dbUser"
            - name: "archburgers.datasource.dbPass"
              valueFrom:
                configMapKeyRef:
                  name: "archburgers-db-access-config"
                  key: "archburgers.datasource.dbPass"

            - name: "archburgers.integration.mercadopago.apiBaseUrl"
              valueFrom:
                configMapKeyRef:
                  name: "archburgers-pagamento-services-config"
                  key: "archburgers.integration.mercadopago.apiBaseUrl"
            - name: "archburgers.integration.mercadopago.userId"
              valueFrom:
                configMapKeyRef:
                  name: "archburgers-pagamento-services-config"
                  key: "archburgers.integration.mercadopago.userId"
            - name: "archburgers.integration.mercadopago.accessToken"
              valueFrom:
                configMapKeyRef:
                  name: "archburgers-pagamento-services-config"
                  key: "archburgers.integration.mercadopago.accessToken"
            - name: "archburgers.integration.mercadopago.posId"
              valueFrom:
                configMapKeyRef:
                  name: "archburgers-pagamento-services-config"
                  key: "archburgers.integration.mercadopago.posId"
            - name: "archburgers.integration.mercadopago.notificationUrl"
              valueFrom:
                configMapKeyRef:
                  name: "archburgers-pagamento-services-config"
                  key: "archburgers.integration.mercadopago.notificationUrl"
          readinessProbe:
            httpGet:
              port: 8090
              path: /healthcheck
            initialDelaySeconds: 20
            periodSeconds: 10
            timeoutSeconds: 3
            failureThreshold: 1
          livenessProbe:
            httpGet:
              port: 8090
              path: /healthcheck
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 3
            # https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/
            # A common pattern for liveness probes is to use the same low-cost HTTP endpoint as for readiness probes,
            # but with a higher failureThreshold
            failureThreshold: 5
          resources:
            requests:
              cpu: 250m


